wifi.setmode(wifi.STATION)
wifi.sta.config("xxx", "xxx", 0)
wifi.setphymode(wifi.PHYMODE_N)
wifi.sleeptype(wifi.MODEM_SLEEP)

wifi.sta.eventMonReg(wifi.STA_IDLE, function()
    print("Wifi STATION_IDLE")
    print("Going to deep sleep")
    tmr.softwd(-1)
    node.dsleep(60*1000000,2)
end) 
wifi.sta.eventMonReg(wifi.STA_CONNECTING, function() print("Wifi STATION_CONNECTING") end)
wifi.sta.eventMonReg(wifi.STA_WRONGPWD, function() print("Wifi STATION_WRONG_PASSWORD") end)
wifi.sta.eventMonReg(wifi.STA_APNOTFOUND, function() print("Wifi STATION_NO_AP_FOUND") end)
wifi.sta.eventMonReg(wifi.STA_FAIL, function() print("Wifi STATION_CONNECT_FAIL") end)
wifi.sta.eventMonReg(wifi.STA_GOTIP, function() 
    print("STATION_GOT_IP")
    print("Refreshing LCD")
    tmr.softwd(60)
    dofile("socketLCD.lua")
end)

wifi.sta.eventMonStart(500)
wifi.sta.connect()
tmr.softwd(60)
